---
  - name: Git checkout do projeto
    ansible.builtin.git:
      repo: 'https://github.com/LeonardoDG2084/iaac_slacko-api.git'
      dest: /opt/slacko-api
      version: master
    notify:
      - Rodando requeriments.txt
      - Criar Service
      - Reiniciar slacko-api      
    tags:
      - instala-projeto